#!/bin/sh
#
# $FreeBSD: branches/2018Q2/news/sabnzbdplus/files/sabnzbd.in 425499 2016-11-06 15:39:54Z riggs $
#
# PROVIDE: sabnzbd
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# sabnzbd_enable (bool):        Set to NO by default.
#                       Set it to YES to enable it.
# sabnzbd_conf_dir:     Directory where sabnzbd configuration
#                       data is stored.
#                       Default: /usr/local/sabnzbd
# sabnzbd_user:         The user account sabnzbd daemon runs as what
#                       you want it to be. It uses '_sabnzbd' user by
#                       default. Do not sets it as empty or it will run
#                       as root.
# sabnzbd_group:        The group account sabnzbd daemon runs as what
#                       you want it to be. It uses '_sabnzbd' group by
#                       default. Do not sets it as empty or it will run
#                       as wheel.
# sabnzbd_pidfile:      Set the location of the sabnzbd pidfile

. /etc/rc.subr

name=sabnzbd
rcvar=sabnzbd_enable
load_rc_config ${name}

: ${sabnzbd_enable:=NO}
: ${sabnzbd_user:=media}
: ${sabnzbd_group:=media}
: ${sabnzbd_conf_dir="/config/sabnzbddata"}
: ${sabnzbd_pidfile:="/config/sabnzbdpid/sabnzbd.pid"}

pidfile=${sabnzbd_pidfile}

start_precmd="${name}_prestart"
command_interpreter="/usr/local/bin/python2.7"
command="/usr/local/bin/SABnzbd.py"
command_args="--daemon -f ${sabnzbd_conf_dir}/sabnzbd.ini --pidfile ${pidfile}"

sabnzbd_prestart()
{
	PATH=${PATH}:/usr/local/bin:/usr/local/sbin
	export LC_CTYPE="en_US.UTF-8"
	for sabdir in ${sabnzbd_conf_dir} ${pidfile%/*}; do
		if [ ! -d "${sabdir}" ]; then
			install -d -o ${sabnzbd_user} -g ${sabnzbd_group} ${sabdir}
		fi
	done
}

run_rc_command "$1"
